---
- name: Deploy Docker container from GHCR
  hosts: all
  become: true

  vars:
    image_name: "ghcr.io/myurukov573/monster-land:latest"
    container_name: "monster-land"

  tasks:
    - name: Login to GHCR
      docker_login:
        registry_url: ghcr.io
        username: "myurukov573"
        password: "{{ ghcr_token }}"

    - name: Pull image from GHCR
      docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: Start or update container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: always
        ports:
          - "80:3000"
