- name: Deploy Docker container from GHCR
  hosts: all
  become: true

  vars:
    image_name: "ghcr.io/myurukov573/monster-land:latest"
    container_name: "monster-land"
    backup_script_path: "/usr/local/bin/jenkins_backup.sh"

  tasks:
    - name: Sync latest code from GitHub repo
      ansible.builtin.git:
        repo: https://github.com/myurukov573/monster-land.git
        dest: /opt/monster-land
        version: main
        force: yes

    - name: Log in to GHCR
      community.docker.docker_login:
        registry_url: ghcr.io
        username: "myurukov573"
        password: "{{ ghcr_token }}"

    - name: Pull latest image
      community.docker.docker_image:
        name: "{{ image_name }}"
        source: pull
        force_source: true

    - name: Ensure container is running
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: always
        ports:
          - "8081:3000"

    - name: Wait for container to be reachable on port 8081
      ansible.builtin.wait_for:
        host: "127.0.0.1"
        port: 8081
        timeout: 30

    - name: Copy Jenkins backup script
      ansible.builtin.copy:
        src: "files/jenkins-backup.sh"
        dest: "{{ backup_script_path }}"
        mode: '0755'
        force: true

    - name: Ensure cron job exists for Jenkins backup
      ansible.builtin.cron:
        name: "Daily Jenkins Backup"
        minute: "0"
        hour: "2"
        job: "{{ backup_script_path }}"
        state: present
